### ISSUE TITLE
[Improvement] Cloudfront - ALB - API server - DB 간 timeout 시간 조정

### ISSUE THREAD

**Issue by RyanBreathings** [newvillagetown/ticketing-backend#11]
### 개선 전 상세 정보
- 기능 & 업무 :  트래픽 통과하는 관문 마다 타임아웃 시간 설정 필요
- 요청자 : @RyanBreathings 

### 개선 이유
Client가 정상적으로 DB conection timeout에러를 받을 수 있도록 timeout시간 조정 필요

### Tasks
- [ ] cloudFront 타임아웃 설정
- [ ] ALB 타임아웃 설정
- [ ] API 서버 타임아웃 설정
- [ ] DB 타임아웃 설정

**Comment by RyanBreathings** [comment]
현재 Cloudfront의 origin connection timeout시간이 API 서버(ALB)의 설정 보다 짧아, 정확한 에러를 반환받지 못함.

각 timeout시간의 길이는 아래와 같아야함
Cloudfront > ALB > API server > DB connection

현재 설정 시간들
Cloudfront : 30초
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/distribution-web-values-specify.html#DownloadDistValuesOriginResponseTimeout

ALB : 60초
https://docs.aws.amazon.com/ko_kr/elasticloadbalancing/latest/application/application-load-balancers.html#connection-idle-timeout

API 서버 :  x

DB 서버 : 8초

**Comment by RyanBreathings** [comment]
### 작업 완료

- 인프라 설정
  - Cloundfront : 30초
  - ALB : 26초
- 소스 내 설정
  - API 서버 : 24초
  - DB 및 외부요청 : 8초
